### PR TITLE
RELATED: ONE-3139 Filtered measure has wrong drill context

### PR DESCRIPTION
**Pull request by ivan-nejezchleb**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/258/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 13s
- gooddata-react-components-unit-tests-zuul-docker-el7 : SKIPPED

**Comment by ivan-nejezchleb** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/259/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 7s
- gooddata-react-components-unit-tests-zuul-docker-el7 : SKIPPED

**Comment by ivan-nejezchleb** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/262/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1501/ : SUCCESS in 2m 05s

**Comment by ivan-nejezchleb** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/264/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1502/ : SUCCESS in 4m 05s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/44/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1503/ : SUCCESS in 1m 42s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/620/ : SUCCESS in 14m 49s

**Pull request merged**
