### PR TITLE
RELATED: BB-862 Truncate long Headline secondary measure title

### PR DESCRIPTION
**Pull request by xMort**

### CODE REVIEW

**Comment by xMort** [comment]
extended test - storybook

**Comment by xMort** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/519/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1543/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/451/ : UNSTABLE in 7m 48s

**Comment by xMort** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1547/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1262/ : SUCCESS in 1m 47s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/735/ : SUCCESS in 2m 26s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/521/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1548/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/454/ : SUCCESS in 7m 46s

**Comment by xMort** [comment]
extended test - deploy

**Comment by osklive-kacatko** [comment]
Demo is running at https://client-demo.na.intgdc.com:50049/storybook/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1549/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/455/ : SUCCESS in 3m 14s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/2/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1268/ : SUCCESS in 1m 15s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/525/ : SUCCESS in 9m 33s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/741/ : SUCCESS in 2m 15s

**Pull request merged**
