### PR TITLE
BUGFIX: RAIL-736 telemetry for KPI doesnt work

### PR DESCRIPTION
**Pull request by tomasreichmann**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/99/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1350/ : SUCCESS in 5m 34s

**Comment by lhorak** [comment]
extended test - storybook

**Comment by yenkins** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/554/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/100/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/476/ : SUCCESS in 9m 18s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/14/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1351/ : SUCCESS in 4m 20s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/555/ : SUCCESS in 10m 12s

**Pull request merged**
