### PR TITLE
RELATED: RAIL-657 Support for multiple domains

### PR DESCRIPTION
**Pull request by vojty**
`@gooddata/react-components@4.0.0-vojty-factory-sdk-2018-03-01T09-57-09-670Z`

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/659/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/538/ : SUCCESS in 2m 03s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/6/ : FAILURE in 5s

**Comment by vojty** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/668/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/548/ : SUCCESS in 2m 10s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/16/ : SUCCESS in 1m 32s

**Comment by zbycz** [comment]
`@gooddata/react-components@4.0.0-pavelzgdc-vojty-factory-sdk-2018-02-23T12-31-59-123Z`

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/712/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/581/ : SUCCESS in 2m 16s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/49/ : SUCCESS in 21s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/747/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/607/ : SUCCESS in 2m 06s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/75/ : SUCCESS in 22s

**Comment by langhammerp** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/751/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/612/ : SUCCESS in 1m 59s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/82/ : SUCCESS in 22s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/752/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/613/ : SUCCESS in 2m 18s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/84/ : SUCCESS in 1m 28s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/753/ : SUCCESS in 37s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/614/ : SUCCESS in 2m 09s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/85/ : SUCCESS in 2m 41s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/163/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/615/ : SUCCESS in 58s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/185/ : SUCCESS in 3m 25s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/86/ : SUCCESS in 2m 09s

**Pull request merged**
