### PR TITLE
test backstop delay

### PR DESCRIPTION
**Pull request by peterlacko**

### CODE REVIEW

**Comment by peterlacko** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1297/ : SUCCESS in 34s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1056/ : FAILURE in 3m 29s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/529/ : SUCCESS in 3m 40s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/404/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1298/ : SUCCESS in 22s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/368/ : UNSTABLE in 10m 26s

**Comment by peterlacko** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1299/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1057/ : SUCCESS in 4m 08s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/530/ : SUCCESS in 5m 21s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/405/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1300/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/369/ : SUCCESS in 8m 41s

**Comment by pbenes** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/406/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1301/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/370/ : UNSTABLE in 8m 56s

**Pull request closed without merging**
