### PR TITLE
RELATED RAIL-1159 New license of GoodData.UI

### PR DESCRIPTION
**Pull request by macekond**

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by xMort** [comment]
lgtm

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/411/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/1242/ : SUCCESS in 1m 43s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/728/ : SUCCESS in 23m 34s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/333/ : FAILURE in 18m 58s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/412/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/1243/ : SUCCESS in 1m 53s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/729/ : SUCCESS in 14m 04s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/334/ : SUCCESS in 7m 24s

**Pull request merged**
