### PR TITLE
FEATURE: ONE-4322 Improve the way how the Grand Total is displayed

### PR DESCRIPTION
**Pull request by patrikbraborec**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/6039/ : FAILURE in 4m 30s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-oss-check/1662/ : SUCCESS in 4s

**Comment by patrikbraborec** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/6101/ : SUCCESS in 8m 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-oss-check/1744/ : SUCCESS in 8s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/6103/ : SUCCESS in 5m 56s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-oss-check/1745/ : SUCCESS in 5s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/6109/ : SUCCESS in 11m 48s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-oss-check/1752/ : SUCCESS in 27s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/6125/ : SUCCESS in 20m 06s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-oss-check/1772/ : SUCCESS in 7s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/6128/ : FAILURE in 4m 11s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-oss-check/1777/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/3167/ : SUCCESS in 19m 24s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/6130/ : SUCCESS in 14m 48s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/1488/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/2086/ : FAILURE in 17m 27s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/3168/ : SUCCESS in 14m 25s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/6131/ : SUCCESS in 10m 28s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/1489/ : SUCCESS in 22s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/2087/ : FAILURE in 13m 03s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/3172/ : SUCCESS in 14m 33s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/6138/ : SUCCESS in 7m 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/1492/ : SUCCESS in 24s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/2098/ : SUCCESS in 19m 21s

**Pull request merged**
