### PR TITLE
RELATED: SETI-1248 run gemini via gdc-ci yaml

### PR DESCRIPTION
**Pull request by langhammerp**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/135/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/771/ : SUCCESS in 2m 15s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/84/ : SUCCESS in 2m 28s (non-voting)

**Comment by langhammerp** [comment]
extended test - gemini

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/136/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/25/ : FAILURE in 30s

**Comment by langhammerp** [comment]
extended test - gemini

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/138/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/26/ : FAILURE in 2m 52s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/137/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/772/ : SUCCESS in 3m 52s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/85/ : SUCCESS in 2m 26s (non-voting)

**Comment by langhammerp** [comment]
extended test - gemini

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/139/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/773/ : SUCCESS in 2m 09s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/86/ : SUCCESS in 2m 51s (non-voting)

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/140/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/27/ : FAILURE in 3m 35s

**Comment by langhammerp** [comment]
extended test - gemini

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/141/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/774/ : SUCCESS in 1m 54s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/87/ : SUCCESS in 2m 42s (non-voting)

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/142/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/28/ : FAILURE in 3m 27s

**Comment by langhammerp** [comment]
extended test - gemini

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/143/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/775/ : SUCCESS in 2m 04s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/88/ : SUCCESS in 2m 52s (non-voting)

**Comment by osklive-kacatko** [comment]
Link to Gemini test result:

https://ci.intgdc.com/job/gooddata-react-components-gemini-zuul/25/artifact/gemini/reports/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/144/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/29/ : FAILURE in 3m 32s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/146/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/777/ : SUCCESS in 4m 00s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/90/ : SUCCESS in 3m 00s (non-voting)

**Comment by langhammerp** [comment]
extended test - gemini

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/147/ : SUCCESS in 24s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/30/ : FAILURE in 27s

**Pull request closed without merging**
