### PR TITLE
BUGFIX: BB-1091 BB-1144 Fix of localization issues

### PR DESCRIPTION
**Pull request by sitina**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/638/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/218/ : SUCCESS in 6m 20s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/125/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/224/ : ABORTED in 28s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/110/ : ABORTED in 57s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/15/ : ABORTED in 1m 10s

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/646/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/225/ : SUCCESS in 1m 35s

**Comment by petrjanu** [comment]
Replacing with https://github.com/gooddata/gooddata-react-components/pull/417 as base should be next-5.2 and rebase was needed

**Comment by gdgate** [comment]
Build failed (check-teardown pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-stop-zuul-docker/9/ : FAILURE in 22s

**Pull request closed without merging**
