### PR TITLE
TRIVIAL: Update translations

### PR DESCRIPTION
**Pull request by patrikbraborec**

### CODE REVIEW

**Comment by patrikbraborec** [comment]
Removed translations was originally removed here: https://github.com/gooddata/gooddata-react-components/pull/1391/files#diff-93b0bca91f878341e551454510c3531aL197

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/6684/ : SUCCESS in 5m 21s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-oss-check/2524/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/3479/ : UNSTABLE in 23m 34s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/6686/ : SUCCESS in 7m 08s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/1614/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/2322/ : SUCCESS in 29m 26s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/3491/ : SUCCESS in 16m 22s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/6701/ : SUCCESS in 5m 40s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/1622/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/2333/ : SUCCESS in 27m 17s

**Comment by gdgate** [comment]
Build failed (check-teardown pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-stop-zuul-docker/1011/ : FAILURE in 57s

**Pull request merged**
