### PR TITLE
RELATED: RAIL-421 yaml & docker

### PR DESCRIPTION
**Pull request by tomasreichmann**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/544/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/452/ : SUCCESS in 2m 44s

**Comment by langhammerp** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/566/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/136/ : FAILURE in 3m 12s

**Comment by langhammerp** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/567/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/137/ : FAILURE in 42s

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/617/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/510/ : SUCCESS in 46s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/618/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/511/ : SUCCESS in 50s

**Comment by langhammerp** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/619/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/153/ : FAILURE in 2m 35s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/620/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/512/ : SUCCESS in 49s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/623/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/514/ : SUCCESS in 45s

**Comment by tomasreichmann** [comment]
extended test - examples

**Comment by osklive-kacatko** [comment]
Demo is running at https://client-demo.na.intgdc.com:50036/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/624/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/155/ : SUCCESS in 2m 25s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/625/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/515/ : SUCCESS in 45s

**Comment by tomasreichmann** [comment]
extended test - examples

**Comment by osklive-kacatko** [comment]
Source code updated. Using staging2.intgdc.com backend now. Demo has already been running at https://client-demo.na.intgdc.com:50036/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/627/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/157/ : SUCCESS in 1m 23s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/628/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/516/ : SUCCESS in 51s

**Comment by tomasreichmann** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/630/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/518/ : SUCCESS in 51s

**Comment by osklive-kacatko** [comment]
Source code updated. Using staging2.intgdc.com backend now. Demo has already been running at https://client-demo.na.intgdc.com:50036/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/631/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/158/ : SUCCESS in 1m 29s

**Comment by tomasreichmann** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/632/ : SUCCESS in 28s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/519/ : SUCCESS in 52s

**Comment by osklive-kacatko** [comment]
Source code updated. Using staging2.intgdc.com backend now. Demo has already been running at https://client-demo.na.intgdc.com:50036/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/633/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/159/ : SUCCESS in 1m 26s

**Comment by tomasreichmann** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/634/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/520/ : SUCCESS in 1m 50s

**Comment by osklive-kacatko** [comment]
Source code updated. Using staging2.intgdc.com backend now. Demo has already been running at https://client-demo.na.intgdc.com:50036/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/635/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/160/ : SUCCESS in 2m 20s

**Comment by langhammerp** [comment]
extended test - examples

**Comment by osklive-kacatko** [comment]
Source code updated. Using staging3.intgdc.com backend now. Demo has already been running at https://client-demo.na.intgdc.com:50036/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/636/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/161/ : SUCCESS in 1m 39s

**Comment by tomasreichmann** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/640/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/524/ : SUCCESS in 52s

**Comment by osklive-kacatko** [comment]
Source code updated. Using staging3.intgdc.com backend now. Demo has already been running at https://client-demo.na.intgdc.com:50036/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/641/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/162/ : SUCCESS in 2m 34s

**Comment by langhammerp** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/156/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/642/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/163/ : SUCCESS in 3m 54s

**Comment by zbycz** [comment]
lgtm

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/646/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/529/ : SUCCESS in 43s

**Comment by zbycz** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/647/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/164/ : FAILURE in 1m 44s

**Comment by tomasreichmann** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/648/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/530/ : SUCCESS in 44s

**Comment by tomasreichmann** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/655/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/167/ : FAILURE in 42s

**Comment by tomasreichmann** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/656/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/536/ : SUCCESS in 2m 05s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/4/ : FAILURE in 1m 18s

**Comment by osklive-kacatko** [comment]
Source code updated. Using staging3.intgdc.com backend now. Demo has already been running at https://client-demo.na.intgdc.com:50036/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/657/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/168/ : SUCCESS in 2m 32s

**Comment by lhorak** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/658/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/537/ : SUCCESS in 1m 58s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/5/ : FAILURE in 2m 45s

**Comment by tomasreichmann** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/661/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/541/ : SUCCESS in 42s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/9/ : FAILURE in 24s

**Comment by osklive-kacatko** [comment]
Source code updated. Using staging3.intgdc.com backend now. Demo has already been running at https://client-demo.na.intgdc.com:50036/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/662/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/169/ : SUCCESS in 1m 36s

**Comment by langhammerp** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/663/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/542/ : SUCCESS in 55s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/10/ : SUCCESS in 1m 37s

**Comment by tomasreichmann** [comment]
extended test - examples

**Comment by osklive-kacatko** [comment]
Source code updated. Using staging3.intgdc.com backend now. Demo has already been running at https://client-demo.na.intgdc.com:50036/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/664/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/170/ : SUCCESS in 1m 31s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/152/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/543/ : SUCCESS in 48s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/162/ : SUCCESS in 2m 24s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/11/ : SUCCESS in 1m 48s

**Pull request merged**
