### PR TITLE
RELATED: RAIL-770 Unwrap execution responses

### PR DESCRIPTION
**Pull request by vojty**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1516/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1244/ : FAILURE in 2m 02s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/717/ : SUCCESS in 2m 28s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1517/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1245/ : SUCCESS in 2m 57s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/718/ : SUCCESS in 2m 54s

**Comment by vojty** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/516/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1518/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/441/ : SUCCESS in 9m 21s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1521/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1248/ : SUCCESS in 1m 23s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/721/ : SUCCESS in 2m 46s

**Comment by vojty** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1539/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1260/ : SUCCESS in 3m 38s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/733/ : SUCCESS in 2m 17s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/517/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/13/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1273/ : SUCCESS in 2m 40s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/746/ : SUCCESS in 2m 27s

**Comment by ocetnik** [comment]
lgtm

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/4/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1279/ : FAILURE in 3m 56s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/527/ : SUCCESS in 10m 36s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/752/ : SUCCESS in 5m 30s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/5/ : SUCCESS in 28s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1283/ : SUCCESS in 2m 51s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/528/ : SUCCESS in 9m 18s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/756/ : SUCCESS in 2m 50s

**Pull request merged**
