### PR TITLE
RELATED: RAIL-255 Storybook visual regression tests

### PR DESCRIPTION
**Pull request by zbycz**
do-not-merge

### CODE REVIEW

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/181/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/815/ : SUCCESS in 2m 27s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/130/ : SUCCESS in 2m 25s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/182/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/816/ : SUCCESS in 6m 42s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/131/ : SUCCESS in 1m 23s (non-voting)

**Comment by langhammerp** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/1/artifact/test-storybook/html-report/index.html

**Comment by zbycz** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/2/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/186/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/34/ : SUCCESS in 3m 43s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/185/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/818/ : SUCCESS in 1m 55s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/133/ : ABORTED in 1h 00m 00s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/187/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/819/ : SUCCESS in 4m 45s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/134/ : SUCCESS in 2m 48s (non-voting)

**Comment by zbycz** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/3/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/188/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/35/ : SUCCESS in 2m 46s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/84/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/820/ : SUCCESS in 1m 00s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/135/ : SUCCESS in 1m 25s (non-voting)

**Pull request merged**
