### PR TITLE
RELATED: RAIL-671 Upgrade data-layer

### PR DESCRIPTION
**Pull request by ocetnik**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/671/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/552/ : SUCCESS in 2m 50s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/20/ : SUCCESS in 2m 27s

**Comment by vaclavbohac** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/167/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/672/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/172/ : SUCCESS in 4m 02s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/156/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/553/ : SUCCESS in 2m 28s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/168/ : SUCCESS in 3m 30s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/21/ : SUCCESS in 1m 29s

**Pull request merged**
