### PR TITLE
Merge gd-merge:release-to-develop into develop

### PR DESCRIPTION
**Pull request by gd-merge**

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-react-components-gate-PR1825

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by yenkins** [comment]
## The code coverage is **the same** after your change 🤟
This is a good thing if you are not sure ;)
#### Report (compared to build [#8340](https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/8340/))
Covered lines: **91.99%**, change: **0%**
Covered branches: **84.04%**, change: **0%**
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/8345/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-fossa-scanning-zuul-el7/275/ : FAILURE in 3m 11s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/2060/ : SUCCESS in 25s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/4397/ : SUCCESS in 14m 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-sonarqube-scan-zuul-gate/42/ : SUCCESS in 3m 16s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/8345/ : SUCCESS in 5m 33s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/3153/ : FAILURE in 21m 46s

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-react-components-gate-PR1825

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by yenkins** [comment]
## The code coverage is **the same** after your change 🤟
This is a good thing if you are not sure ;)
#### Report (compared to build [#8345](https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/8345/))
Covered lines: **91.99%**, change: **0%**
Covered branches: **84.04%**, change: **0%**
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/8346/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-fossa-scanning-zuul-el7/276/ : FAILURE in 3m 06s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/2061/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/4398/ : UNSTABLE in 16m 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-sonarqube-scan-zuul-gate/43/ : SUCCESS in 4m 11s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/8346/ : SUCCESS in 4m 21s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/3154/ : SUCCESS in 19m 06s

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-react-components-gate-PR1825

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by yenkins** [comment]
## The code coverage is **the same** after your change 🤟
This is a good thing if you are not sure ;)
#### Report (compared to build [#8346](https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/8346/))
Covered lines: **91.99%**, change: **0%**
Covered branches: **84.04%**, change: **0%**
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/8347/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-fossa-scanning-zuul-el7/277/ : FAILURE in 3m 32s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/2062/ : SUCCESS in 21s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/4399/ : SUCCESS in 12m 07s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-sonarqube-scan-zuul-gate/44/ : SUCCESS in 5m 12s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/8347/ : SUCCESS in 10m 38s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/3155/ : FAILURE in 27m 07s

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-react-components-gate-PR1825

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by yenkins** [comment]
## The code coverage is **the same** after your change 🤟
This is a good thing if you are not sure ;)
#### Report (compared to build [#8347](https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/8347/))
Covered lines: **91.99%**, change: **0%**
Covered branches: **84.04%**, change: **0%**
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/8350/artifact/ci/results/coverage/lcov-report/index.html

**Comment by yenkins** [comment]
## The code coverage is **the same** after your change 🤟
This is a good thing if you are not sure ;)
#### Report (compared to build [#8350](https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/8350/))
Covered lines: **91.99%**, change: **0%**
Covered branches: **84.04%**, change: **0%**
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/8351/artifact/ci/results/coverage/lcov-report/index.html

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-react-components-gate-PR1825

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-fossa-scanning-zuul-el7/281/ : FAILURE in 2m 39s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/2066/ : SUCCESS in 21s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/4403/ : SUCCESS in 12m 25s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-sonarqube-scan-zuul-gate/48/ : SUCCESS in 3m 28s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/8351/ : SUCCESS in 3m 29s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/3159/ : SUCCESS in 16m 44s

**Pull request merged**
