### PR TITLE
RELATED: BB-334 Totals edit mode

### PR DESCRIPTION
**Pull request by petrjanu**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/150/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/781/ : SUCCESS in 2m 14s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/94/ : SUCCESS in 2m 26s (non-voting)

**Comment by petrjanu** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/151/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/782/ : SUCCESS in 2m 03s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/95/ : SUCCESS in 2m 29s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/162/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/796/ : SUCCESS in 2m 09s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/109/ : SUCCESS in 2m 09s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/163/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/797/ : SUCCESS in 2m 21s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/110/ : SUCCESS in 2m 14s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/169/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/803/ : SUCCESS in 1m 52s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/116/ : SUCCESS in 2m 40s (non-voting)

**Comment by petrjanu** [comment]
extended test - gemini

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/170/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/31/ : FAILURE in 8m 38s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/189/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/821/ : SUCCESS in 2m 26s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/136/ : SUCCESS in 2m 52s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/190/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/822/ : SUCCESS in 6m 29s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/137/ : ABORTED in 1h 00m 03s (non-voting)

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/194/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/826/ : FAILURE in 7m 24s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/141/ : ABORTED in 17m 23s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/199/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/834/ : SUCCESS in 2m 09s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/149/ : SUCCESS in 3m 15s (non-voting)

**Comment by petrjanu** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/4/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/200/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/36/ : UNSTABLE in 4m 56s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/201/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/835/ : SUCCESS in 1m 02s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/150/ : SUCCESS in 1m 23s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/202/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/836/ : SUCCESS in 1m 03s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/151/ : SUCCESS in 1m 22s (non-voting)

**Comment by petrjanu** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/5/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/203/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/37/ : UNSTABLE in 3m 55s

**Comment by petrjanu** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/204/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/837/ : SUCCESS in 2m 17s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/152/ : SUCCESS in 1m 26s (non-voting)

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/6/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/205/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/38/ : SUCCESS in 2m 41s

**Comment by petrjanu** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/206/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/838/ : SUCCESS in 1m 05s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/153/ : FAILURE in 2m 02s (non-voting)

**Comment by petrjanu** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/207/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/839/ : SUCCESS in 1m 02s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/154/ : SUCCESS in 5m 27s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/210/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/843/ : SUCCESS in 2m 03s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/158/ : SUCCESS in 2m 24s (non-voting)

**Comment by petrjanu** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/7/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/211/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/39/ : UNSTABLE in 4m 01s

**Comment by petrjanu** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/212/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/844/ : SUCCESS in 2m 51s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/159/ : SUCCESS in 2m 51s (non-voting)

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/8/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/213/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/40/ : SUCCESS in 4m 06s

**Comment by petrjanu** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/214/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/845/ : SUCCESS in 1m 03s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/160/ : SUCCESS in 1m 24s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/89/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/846/ : SUCCESS in 2m 34s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/161/ : SUCCESS in 1m 25s (non-voting)

**Pull request merged**
