### PR TITLE
BUGFIX: BB-544 Fix German string for Rollup

### PR DESCRIPTION
**Pull request by tomassatinsky**

### CODE REVIEW

**Comment by tomassatinsky** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/318/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/240/ : SUCCESS in 1m 39s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/53/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/319/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/79/ : SUCCESS in 4m 13s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/104/ : SUCCESS in 22s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/242/ : SUCCESS in 1m 33s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/55/ : SUCCESS in 2m 41s

**Pull request merged**
