### PR TITLE
RELATED: RAIL-551 checkEmptyResults checks if executionResult.data are empty instead of the whole executionResult

### PR DESCRIPTION
**Pull request by tomasreichmann**

### CODE REVIEW

**Comment by tomasreichmann** [comment]
extended test - gemini

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/177/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/32/ : FAILURE in 37s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/176/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/810/ : SUCCESS in 2m 00s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/125/ : ABORTED in 7m 25s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/83/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/812/ : SUCCESS in 53s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/127/ : ABORTED in 2m 42s (non-voting)

**Pull request merged**
