### PR TITLE
RELATED: RAIL-647 add SDK telemetry

### PR DESCRIPTION
**Pull request by zbycz**
PRs:
https://github.com/gooddata/gooddata-js/pull/246
https://github.com/gooddata/gooddata-react-components/pull/204

### CODE REVIEW

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/760/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/618/ : FAILURE in 1m 57s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/89/ : SUCCESS in 21s

**Comment by zbycz** [comment]
extended test - examples

**Comment by osklive-kacatko** [comment]
Demo is running at https://client-demo.na.intgdc.com:50026/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/761/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/200/ : SUCCESS in 3m 18s

**Comment by zbycz** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/762/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/619/ : FAILURE in 55s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/90/ : FAILURE in 1m 13s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/763/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/201/ : FAILURE in 1m 38s

**Comment by zbycz** [comment]
extended test - examples

**Pull request closed without merging**
