### PR TITLE
RELATED: FET-48 React 15.6.2

### PR DESCRIPTION
**Pull request by vojty**

### CODE REVIEW

**Comment by ocetnik** [comment]
extended test - examples

**Comment by osklive-kacatko** [comment]
Demo is running at https://client-demo.na.intgdc.com:50015/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/850/ : SUCCESS in 43s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/226/ : SUCCESS in 5m 18s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/177/ : SUCCESS in 19s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/691/ : SUCCESS in 2m 05s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/217/ : SUCCESS in 3m 54s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/162/ : SUCCESS in 2m 21s

**Pull request merged**
