### PR TITLE
RELATED: RAIL-746 Add changelog.md

### PR DESCRIPTION
**Pull request by zbycz**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/269/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1136/ : SUCCESS in 4m 48s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/467/ : FAILURE in 1m 56s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/609/ : SUCCESS in 2m 59s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1381/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1134/ : FAILURE in 4m 16s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/607/ : SUCCESS in 6m 14s

**Comment by ocetnik** [comment]
lgtm

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/270/ : SUCCESS in 31s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1137/ : FAILURE in 3m 32s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/469/ : UNSTABLE in 8m 54s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/610/ : SUCCESS in 12m 11s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/271/ : SUCCESS in 26s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1138/ : FAILURE in 4m 47s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/470/ : SUCCESS in 8m 46s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/611/ : SUCCESS in 2m 36s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/272/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1139/ : SUCCESS in 2m 43s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/471/ : UNSTABLE in 7m 37s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/612/ : SUCCESS in 4m 37s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/274/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1144/ : SUCCESS in 2m 37s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/473/ : UNSTABLE in 8m 08s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/617/ : SUCCESS in 2m 38s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/275/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1146/ : SUCCESS in 1m 14s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/475/ : SUCCESS in 8m 27s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/619/ : SUCCESS in 2m 45s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/276/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1150/ : SUCCESS in 1m 06s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/479/ : SUCCESS in 6m 52s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/623/ : FAILURE in 2m 14s

**Pull request merged**
