### PR TITLE
RAIL-421 Verification

### PR DESCRIPTION
**Pull request by vaclavbohac**

### CODE REVIEW

**Comment by vaclavbohac** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/673/ : SUCCESS in 23s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/554/ : SUCCESS in 58s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/22/ : SUCCESS in 23s

**Comment by osklive-kacatko** [comment]
Demo is running at https://client-demo.na.intgdc.com:50031/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/674/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/173/ : SUCCESS in 2m 54s

**Pull request closed without merging**
