### PR TITLE
TRIVIAL: Update translations

### PR DESCRIPTION
**Pull request by patrikbraborec**

### CODE REVIEW

**Comment by petrjanu** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/6590/ : SUCCESS in 9m 59s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-oss-check/2419/ : SUCCESS in 10s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/3436/ : UNSTABLE in 23m 21s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/6604/ : SUCCESS in 7m 45s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/1593/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/2294/ : SUCCESS in 23m 05s

**Comment by strouhaljan** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/3438/ : SUCCESS in 22m 44s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/6605/ : SUCCESS in 12m 25s
- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/1594/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/2295/ : SUCCESS in 25m 30s

**Pull request merged**
