### PR TITLE
RELATED: ONE-3017 Allow getting deprecated visualization classes

### PR DESCRIPTION
**Pull request by ZdenekVidensky**

### CODE REVIEW

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1233/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1002/ : SUCCESS in 2m 31s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/475/ : SUCCESS in 3m 24s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1252/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1015/ : SUCCESS in 3m 05s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/488/ : SUCCESS in 3m 30s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/223/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1016/ : SUCCESS in 1m 25s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/367/ : FAILURE in 3m 58s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/489/ : SUCCESS in 2m 48s

**Comment by ZdenekVidensky** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/368/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1254/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/348/ : UNSTABLE in 7m 35s

**Comment by ZdenekVidensky** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/369/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1256/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/349/ : SUCCESS in 6m 29s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/225/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1023/ : SUCCESS in 1m 36s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/372/ : FAILURE in 3m 17s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/496/ : SUCCESS in 3m 16s

**Pull request closed without merging**
