### PR TITLE
BUGFIX RAIL-713 Loading component does not work in Firefox

### PR DESCRIPTION
**Pull request by tomasreichmann**

### CODE REVIEW

**Comment by tomasreichmann** [comment]
ok to test

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1009/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/814/ : SUCCESS in 57s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/287/ : SUCCESS in 2m 09s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/284/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1010/ : SUCCESS in 1m 11s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/283/ : SUCCESS in 5m 23s

**Comment by tomasreichmann** [comment]
ok to test

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1011/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/815/ : SUCCESS in 56s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/288/ : SUCCESS in 2m 25s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/285/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1012/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/284/ : UNSTABLE in 4m 31s

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/286/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1013/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/285/ : UNSTABLE in 4m 39s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1014/ : SUCCESS in 24s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/816/ : SUCCESS in 1m 13s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/289/ : SUCCESS in 2m 59s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/287/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1015/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/286/ : SUCCESS in 4m 25s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/198/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/819/ : SUCCESS in 1m 01s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/288/ : UNSTABLE in 5m 06s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/292/ : SUCCESS in 2m 22s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/199/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/825/ : SUCCESS in 54s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/290/ : SUCCESS in 3m 37s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/298/ : SUCCESS in 2m 16s

**Pull request merged**
