### PR TITLE
RELATED: ONE-2815 Allow disabling gridline

### PR DESCRIPTION
**Pull request by peterlacko**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1235/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1006/ : SUCCESS in 3m 03s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/479/ : SUCCESS in 2m 54s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/392/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1282/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/361/ : UNSTABLE in 8m 53s

**Comment by pbenes** [comment]
Add storybook (and consider adding it to test suite)

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/235/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1043/ : SUCCESS in 3m 36s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/393/ : SUCCESS in 7m 44s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/516/ : SUCCESS in 3m 21s

**Pull request merged**
