### PR TITLE
RELATED: BB-774 Rename SP translation

### PR DESCRIPTION
**Pull request by petrjanu**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/366/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1601/ : SUCCESS in 1m 38s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/61/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1602/ : SUCCESS in 1m 39s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/650/ : ABORTED in 1m 52s

**Comment by xMort** [comment]
lgtm

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/63/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1605/ : SUCCESS in 1m 43s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/652/ : SUCCESS in 15m 17s

**Pull request merged**
