### PR TITLE
TRIVIAL: Update readme to npm publish --access=public

### PR DESCRIPTION
**Pull request by BugsBunny338**

### CODE REVIEW

**Comment by BugsBunny338** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/27/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/663/ : SUCCESS in 1m 46s

**Comment by BugsBunny338** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/29/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/665/ : SUCCESS in 49s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/30/ : SUCCESS in 1m 09s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/666/ : SUCCESS in 52s

**Comment by BugsBunny338** [comment]
Closed in favor of https://github.com/gooddata/gooddata-react-components/pull/98.

**Pull request closed without merging**
