### PR TITLE
RELATED: RAIL-343 Default event parameters for Execute component

### PR DESCRIPTION
**Pull request by vojty**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/148/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/779/ : SUCCESS in 1m 48s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/92/ : SUCCESS in 2m 33s (non-voting)

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/149/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/780/ : FAILURE in 3m 58s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/93/ : SUCCESS in 1m 58s (non-voting)

**Comment by vojty** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/159/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/791/ : SUCCESS in 1m 50s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/104/ : SUCCESS in 2m 14s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/160/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/792/ : SUCCESS in 54s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/105/ : SUCCESS in 2m 46s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/78/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/793/ : SUCCESS in 1m 46s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/106/ : SUCCESS in 2m 14s (non-voting)

**Pull request merged**
