### PR TITLE
TSA test vis obj conversion

### PR DESCRIPTION
**Pull request by tomassatinsky**
created just to make demo

### CODE REVIEW

**Comment by tomassatinsky** [comment]
extended test - deploy

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/622/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/154/ : FAILURE in 10s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/621/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/513/ : SUCCESS in 2m 22s

**Comment by tomassatinsky** [comment]
extended test - deploy

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/626/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/156/ : FAILURE in 39s

**Pull request closed without merging**
