### PR TITLE
RELATED: SETI-1248 run gemini via gdc-ci yaml

### PR DESCRIPTION
**Pull request by langhammerp**

### CODE REVIEW

**Comment by langhammerp** [comment]
extended test - gemini

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/124/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/762/ : SUCCESS in 5m 06s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/74/ : SUCCESS in 2m 12s (non-voting)

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/125/ : SUCCESS in 59s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/23/ : FAILURE in 5m 13s

**Comment by langhammerp** [comment]
extended test - gemini

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/129/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/24/ : FAILURE in 1m 09s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/128/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/765/ : SUCCESS in 2m 08s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/77/ : SUCCESS in 2m 41s (non-voting)

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/132/ : SUCCESS in 1m 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/769/ : FAILURE in 35s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/81/ : FAILURE in 17s (non-voting)

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/134/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/770/ : FAILURE in 7m 09s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/83/ : FAILURE in 2m 07s (non-voting)

**Pull request closed without merging**
