### PR TITLE
FEATURE: BB-692 Insight over time support in visualizations

### PR DESCRIPTION
**Pull request by tomassatinsky**

### CODE REVIEW

**Comment by tomassatinsky** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1279/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1040/ : SUCCESS in 1m 13s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/513/ : SUCCESS in 2m 19s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/390/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1280/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/360/ : UNSTABLE in 8m 31s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1313/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1080/ : SUCCESS in 4m 30s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/553/ : SUCCESS in 3m 55s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1314/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1081/ : SUCCESS in 1m 58s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/554/ : SUCCESS in 2m 48s

**Comment by petrjanu** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/423/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1315/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/374/ : UNSTABLE in 9m 00s

**Comment by petrjanu** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/426/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1316/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/375/ : UNSTABLE in 9m 24s

**Comment by petrjanu** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1321/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1087/ : SUCCESS in 1m 45s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/560/ : SUCCESS in 3m 31s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/428/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1322/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/377/ : UNSTABLE in 10m 05s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1325/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1089/ : SUCCESS in 1m 20s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/562/ : SUCCESS in 2m 34s

**Comment by xMort** [comment]
lgtm

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/256/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1090/ : FAILURE in 1m 33s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/430/ : UNSTABLE in 9m 01s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/563/ : SUCCESS in 5m 03s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/257/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1092/ : SUCCESS in 1m 36s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/431/ : UNSTABLE in 7m 16s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/565/ : SUCCESS in 2m 24s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/258/ : SUCCESS in 19s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1093/ : FAILURE in 2m 52s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/432/ : SUCCESS in 7m 02s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/566/ : SUCCESS in 4m 04s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/259/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1094/ : SUCCESS in 3m 50s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/433/ : UNSTABLE in 8m 24s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/567/ : SUCCESS in 2m 33s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/260/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1095/ : FAILURE in 1m 42s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/434/ : UNSTABLE in 6m 47s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/568/ : SUCCESS in 2m 29s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/261/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1096/ : FAILURE in 1m 41s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/435/ : SUCCESS in 6m 37s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/569/ : SUCCESS in 2m 34s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/262/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1097/ : SUCCESS in 1m 16s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/436/ : SUCCESS in 8m 08s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/570/ : SUCCESS in 2m 24s

**Pull request merged**
