### PR TITLE
RELATED: RAIL-341 add docker .config

### PR DESCRIPTION
**Pull request by langhammerp**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/40/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/679/ : SUCCESS in 51s

**Comment by langhammerp** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/53/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/694/ : SUCCESS in 2m 00s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1/ : SUCCESS in 2m 44s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/73/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/695/ : SUCCESS in 1m 49s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/2/ : SUCCESS in 1m 20s (non-voting)

**Pull request merged**
