### PR TITLE
TRIVIAL: RAIL-1078 - Hide pivot table from examples menu

### PR DESCRIPTION
**Pull request by lhorak**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/794/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 10s
- gooddata-react-components-unit-tests-zuul-docker-el7 : SKIPPED

**Comment by lhorak** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/795/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 7s
- gooddata-react-components-unit-tests-zuul-docker-el7 : SKIPPED

**Comment by lhorak** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/799/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/337/ : FAILURE in 2m 37s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/802/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/340/ : SUCCESS in 2m 00s

**Comment by gdgate** [comment]
Build failed (check-teardown pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-stop-zuul-docker/70/ : FAILURE in 37s

**Pull request merged**
