### PR TITLE
FEATURE: RAIL-678 Property default for loading and error

### PR DESCRIPTION
**Pull request by tomasreichmann**

### CODE REVIEW

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/897/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/731/ : FAILURE in 2m 02s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/204/ : UNSTABLE in 27s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/900/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/735/ : SUCCESS in 2m 21s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/208/ : UNSTABLE in 24s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/901/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/736/ : SUCCESS in 56s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/209/ : SUCCESS in 26s

**Comment by tomasreichmann** [comment]
extended test - examples

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Demo is running at https://client-demo.na.intgdc.com:50038/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/903/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/241/ : SUCCESS in 4m 21s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/238/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/905/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/242/ : UNSTABLE in 4m 12s

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/944/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/767/ : FAILURE in 3m 34s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/240/ : SUCCESS in 2m 33s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/255/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/945/ : SUCCESS in 31s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/259/ : UNSTABLE in 5m 23s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/950/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/773/ : SUCCESS in 1m 22s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/246/ : SUCCESS in 2m 33s

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/951/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/261/ : FAILURE in 1m 50s

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/952/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/262/ : FAILURE in 1m 40s

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/953/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/774/ : SUCCESS in 1m 07s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/247/ : SUCCESS in 2m 13s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/261/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/954/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/263/ : UNSTABLE in 3m 58s

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/262/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/955/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/264/ : UNSTABLE in 5m 53s

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by tomasreichmann** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/956/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/775/ : SUCCESS in 1m 00s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/248/ : SUCCESS in 2m 30s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/263/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/957/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/265/ : UNSTABLE in 4m 29s

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/958/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/776/ : SUCCESS in 2m 38s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/249/ : SUCCESS in 3m 08s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/264/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/959/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/266/ : UNSTABLE in 6m 01s

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/960/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/777/ : SUCCESS in 2m 51s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/250/ : SUCCESS in 2m 32s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/265/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/961/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/267/ : UNSTABLE in 6m 03s

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/962/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/778/ : SUCCESS in 1m 02s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/251/ : SUCCESS in 2m 27s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/266/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/963/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/268/ : UNSTABLE in 4m 10s

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/966/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/781/ : SUCCESS in 2m 18s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/254/ : SUCCESS in 2m 14s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/267/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/967/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/269/ : UNSTABLE in 5m 35s

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/968/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/782/ : SUCCESS in 2m 28s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/255/ : SUCCESS in 2m 31s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/268/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/969/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/270/ : UNSTABLE in 5m 47s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/970/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/783/ : SUCCESS in 1m 05s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/256/ : SUCCESS in 2m 43s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/269/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/971/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/271/ : SUCCESS in 3m 58s

**Comment by tomasreichmann** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/972/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/784/ : FAILURE in 1m 24s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/257/ : SUCCESS in 2m 16s

**Comment by tomasreichmann** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/973/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/785/ : SUCCESS in 1m 40s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/258/ : SUCCESS in 2m 42s

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/975/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/787/ : SUCCESS in 2m 21s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/260/ : FAILURE in 2m 49s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/270/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/976/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/272/ : SUCCESS in 6m 27s

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/977/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/788/ : SUCCESS in 55s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/261/ : SUCCESS in 2m 12s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/271/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/978/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/273/ : SUCCESS in 3m 56s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/984/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/793/ : SUCCESS in 58s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/266/ : SUCCESS in 2m 20s

**Comment by tomasreichmann** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/985/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/275/ : FAILURE in 1m 53s

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/273/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/986/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/276/ : UNSTABLE in 4m 02s

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/987/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/794/ : SUCCESS in 1m 03s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/267/ : SUCCESS in 2m 12s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/274/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/988/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/277/ : SUCCESS in 4m 04s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/195/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/799/ : SUCCESS in 3m 41s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/279/ : UNSTABLE in 6m 24s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/272/ : SUCCESS in 3m 21s

**Comment by tomasreichmann** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/996/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/801/ : SUCCESS in 55s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/274/ : SUCCESS in 2m 11s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/280/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/997/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/281/ : SUCCESS in 5m 21s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/196/ : SUCCESS in 36s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/803/ : SUCCESS in 2m 22s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/281/ : SUCCESS in 5m 09s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/276/ : SUCCESS in 2m 32s

**Pull request merged**
