### PR TITLE
RELATED: RAIL-560 Expose chart.reflow() from SDK components

### PR DESCRIPTION
**Pull request by zbycz**
indigo:
https://github.com/gooddata/gooddata-indigo-visualizations/pull/222

### CODE REVIEW

**Comment by zbycz** [comment]
ok to test

**Comment by zbycz** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/232/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/856/ : SUCCESS in 2m 12s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/171/ : SUCCESS in 3m 19s (non-voting)

**Comment by zbycz** [comment]
Closed via https://github.com/gooddata/gooddata-js-boilerplate/pull/18

**Pull request closed without merging**
