### PR TITLE
RELATED: FET-50 Upgrade @gooddata/test-storybook

### PR DESCRIPTION
**Pull request by ocetnik**

### CODE REVIEW

**Comment by ocetnik** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/868/ : SUCCESS in 30s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/706/ : SUCCESS in 3m 59s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/177/ : SUCCESS in 43s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/222/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/869/ : SUCCESS in 25s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/231/ : SUCCESS in 5m 07s

**Comment by ocetnik** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/872/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/710/ : SUCCESS in 2m 21s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/181/ : SUCCESS in 25s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/226/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/873/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/233/ : SUCCESS in 4m 18s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/181/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/711/ : SUCCESS in 2m 17s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/227/ : SUCCESS in 4m 16s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/182/ : SUCCESS in 25s

**Pull request merged**
