### PR TITLE
RELATED: BB-497 dependencies

### PR DESCRIPTION
**Pull request by strouhaljan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/870/ : SUCCESS in 1m 15s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/707/ : SUCCESS in 2m 08s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/178/ : SUCCESS in 2m 22s

**Comment by petrjanu** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/223/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/179/ : SUCCESS in 41s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/708/ : SUCCESS in 2m 11s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/224/ : UNSTABLE in 3m 04s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/179/ : SUCCESS in 1m 51s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/180/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/709/ : SUCCESS in 1m 00s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/225/ : SUCCESS in 4m 18s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/180/ : SUCCESS in 1m 28s

**Pull request merged**
