### PR TITLE
RELATED: BB-534 Fix totals NaN value

### PR DESCRIPTION
**Pull request by tomassatinsky**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/515/ : SUCCESS in 26s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/421/ : SUCCESS in 2m 42s

**Comment by tomassatinsky** [comment]
extended test - cafe

**Comment by tomassatinsky** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/516/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/130/ : FAILURE in 16s

**Comment by tomassatinsky** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/139/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/517/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/131/ : SUCCESS in 4m 21s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/139/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/422/ : SUCCESS in 1m 35s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/140/ : SUCCESS in 4m 04s

**Pull request merged**
