### PR TITLE
RELATED: FEATURE: FET-89 Fix drilling

### PR DESCRIPTION
**Pull request by pbenes**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1508/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1237/ : FAILURE in 44s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/710/ : SUCCESS in 2m 22s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1509/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1238/ : FAILURE in 6m 46s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/711/ : SUCCESS in 5m 42s

**Comment by ivan-nejezchleb** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1511/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1239/ : SUCCESS in 3m 40s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/712/ : SUCCESS in 3m 32s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/280/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1240/ : SUCCESS in 2m 53s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/514/ : SUCCESS in 10m 21s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/713/ : SUCCESS in 4m 30s

**Pull request merged**
