### PR TITLE
RELATED: FET-53 Add DL from gooddata-js

### PR DESCRIPTION
**Pull request by vaclavbohac**
`5.0.0-vaclavbohac-gooddata-ts-integration-2018-04-04T11-10-49-840Z`

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1059/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/841/ : FAILURE in 2m 08s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/314/ : SUCCESS in 2m 10s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1060/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/842/ : FAILURE in 1m 48s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/315/ : SUCCESS in 2m 07s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1061/ : SUCCESS in 39s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/843/ : FAILURE in 2m 01s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/316/ : SUCCESS in 2m 10s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1062/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/844/ : FAILURE in 1m 52s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/317/ : SUCCESS in 2m 12s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1064/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/846/ : SUCCESS in 2m 40s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/319/ : SUCCESS in 3m 10s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1065/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/847/ : SUCCESS in 2m 44s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/320/ : SUCCESS in 2m 28s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1070/ : SUCCESS in 26s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/850/ : SUCCESS in 2m 13s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/323/ : SUCCESS in 3m 01s

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by vaclavbohac** [comment]
`5.0.0-vaclavbohac-gooddata-ts-integration-2018-03-27T13-41-55-743Z`

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1083/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/862/ : FAILURE in 4m 37s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/335/ : SUCCESS in 2m 33s

**Comment by vaclavbohac** [comment]
`5.0.0-vaclavbohac-gooddata-ts-integration-2018-03-27T14-02-31-836Z`

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1085/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/864/ : SUCCESS in 3m 03s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/337/ : SUCCESS in 2m 52s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1126/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/906/ : FAILURE in 2m 15s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/379/ : SUCCESS in 2m 09s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1127/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/907/ : FAILURE in 1m 30s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/380/ : FAILURE in 1m 47s

**Comment by vaclavbohac** [comment]
`5.0.0-vaclavbohac-gooddata-ts-integration-2018-04-04T11-02-58-082Z`

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1128/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/908/ : FAILURE in 1m 54s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/381/ : SUCCESS in 2m 29s

**Comment by vaclavbohac** [comment]
`5.0.0-vaclavbohac-gooddata-ts-integration-2018-04-04T11-10-49-840Z`

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1129/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/909/ : SUCCESS in 2m 25s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/382/ : SUCCESS in 2m 24s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1156/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/928/ : SUCCESS in 5m 00s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/401/ : SUCCESS in 5m 17s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/209/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/929/ : SUCCESS in 5m 03s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/331/ : UNSTABLE in 6m 49s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/402/ : SUCCESS in 2m 34s

**Comment by vaclavbohac** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/332/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1158/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/324/ : SUCCESS in 6m 03s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/210/ : SUCCESS in 26s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/931/ : SUCCESS in 1m 03s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/333/ : SUCCESS in 6m 10s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/404/ : SUCCESS in 2m 22s

**Pull request merged**
