### PR TITLE
RELATED: BB-670 Fix storybook after mock-js Totals support added

### PR DESCRIPTION
**Pull request by petrjanu**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/756/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/616/ : SUCCESS in 2m 15s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/87/ : SUCCESS in 38s

**Comment by petrjanu** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/186/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/757/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/198/ : UNSTABLE in 5m 07s

**Comment by petrjanu** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/758/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/617/ : SUCCESS in 2m 44s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/88/ : SUCCESS in 36s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/187/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/759/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/199/ : UNSTABLE in 4m 14s

**Comment by petrjanu** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/768/ : SUCCESS in 24s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/622/ : SUCCESS in 2m 02s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/93/ : SUCCESS in 28s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/188/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/769/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/204/ : UNSTABLE in 4m 24s

**Comment by petrjanu** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/770/ : SUCCESS in 22s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/623/ : SUCCESS in 2m 24s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/94/ : FAILURE in 1m 42s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/189/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/771/ : SUCCESS in 22s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/205/ : SUCCESS in 2m 37s

**Comment by petrjanu** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/772/ : SUCCESS in 23s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/624/ : SUCCESS in 51s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/95/ : SUCCESS in 25s

**Comment by petrjanu** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/786/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/634/ : SUCCESS in 2m 16s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/105/ : SUCCESS in 21s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/191/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/787/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/207/ : SUCCESS in 4m 32s

**Comment by tomassatinsky** [comment]
lgtm

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/165/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/635/ : FAILURE in 1m 11s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/192/ : SUCCESS in 3m 21s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/106/ : SUCCESS in 1m 46s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/166/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/636/ : SUCCESS in 59s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/193/ : SUCCESS in 2m 14s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/107/ : SUCCESS in 28s

**Pull request merged**
