### PR TITLE
RELATED: FET-68 rename pkg to @gooddata/gooddata-js

### PR DESCRIPTION
**Pull request by zbycz**

### CODE REVIEW

**Comment by zbycz** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1305/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1066/ : SUCCESS in 5m 45s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/539/ : SUCCESS in 3m 25s

**Comment by osklive-kacatko** [comment]
Demo is running at https://client-demo.na.intgdc.com:50038/storybook/

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1306/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/371/ : FAILURE in 5m 20s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/415/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1308/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/372/ : UNSTABLE in 7m 27s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1309/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1072/ : FAILURE in 4m 47s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/545/ : SUCCESS in 2m 41s

**Comment by vaclavbohac** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1310/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1073/ : SUCCESS in 1m 56s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/546/ : SUCCESS in 3m 30s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/249/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1074/ : SUCCESS in 2m 20s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/417/ : FAILURE in 4m 22s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/547/ : SUCCESS in 3m 51s

**Comment by vaclavbohac** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/418/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1311/ : SUCCESS in 19s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/373/ : SUCCESS in 8m 45s

**Comment by vaclavbohac** [comment]
lgtm

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/250/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1075/ : SUCCESS in 2m 25s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/419/ : UNSTABLE in 8m 44s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/548/ : SUCCESS in 3m 23s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/251/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1077/ : SUCCESS in 1m 48s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/420/ : FAILURE in 1m 54s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/550/ : SUCCESS in 5m 10s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/252/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1078/ : SUCCESS in 1m 21s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/421/ : UNSTABLE in 8m 39s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/551/ : SUCCESS in 4m 07s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/253/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1079/ : SUCCESS in 2m 10s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/422/ : FAILURE in 1m 51s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/552/ : SUCCESS in 5m 30s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/254/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1082/ : FAILURE in 2m 29s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/424/ : UNSTABLE in 8m 07s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/555/ : SUCCESS in 3m 45s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/255/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1083/ : SUCCESS in 2m 29s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/425/ : SUCCESS in 7m 31s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/556/ : SUCCESS in 2m 46s

**Pull request merged**
