### PR TITLE
RELATED: BB-501 Fix broken totals highlight

### PR DESCRIPTION
**Pull request by tomassatinsky**
Demo using this version is running at https://client-demo.na.intgdc.com:50028/analyze/

### CODE REVIEW

**Comment by tomassatinsky** [comment]
extended test - deploy

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/878/ : SUCCESS in 21s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/717/ : SUCCESS in 2m 02s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/188/ : SUCCESS in 1m 41s

**Comment by martinmosko** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Demo is running at https://client-demo.na.intgdc.com:50036/storybook/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/879/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/234/ : SUCCESS in 4m 01s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/184/ : SUCCESS in 36s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/721/ : SUCCESS in 1m 02s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/230/ : SUCCESS in 3m 45s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/192/ : SUCCESS in 2m 23s

**Pull request merged**
