### PR TITLE
RELATED: BB-510 Totals edit MSIE fix

### PR DESCRIPTION
**Pull request by petrjanu**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/235/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/859/ : SUCCESS in 1m 57s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/174/ : SUCCESS in 2m 26s (non-voting)

**Comment by petrjanu** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/15/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/236/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/49/ : SUCCESS in 4m 22s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/90/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/860/ : SUCCESS in 2m 08s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/175/ : SUCCESS in 1m 24s (non-voting)

**Pull request merged**
