### PR TITLE
RELATED: BB-501 find last added total row and pass it down

### PR DESCRIPTION
**Pull request by strouhaljan**

### CODE REVIEW

**Comment by strouhaljan** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/725/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/591/ : SUCCESS in 2m 00s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/59/ : SUCCESS in 1m 24s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/179/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/726/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/189/ : SUCCESS in 3m 57s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/731/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/594/ : FAILURE in 24s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/62/ : SUCCESS in 22s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/738/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/597/ : SUCCESS in 2m 12s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/65/ : SUCCESS in 1m 20s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/740/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/599/ : SUCCESS in 59s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/67/ : SUCCESS in 1m 23s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/743/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/603/ : FAILURE in 1m 44s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/71/ : SUCCESS in 21s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/744/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/604/ : SUCCESS in 47s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/72/ : SUCCESS in 20s

**Comment by strouhaljan** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/181/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/745/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/196/ : SUCCESS in 3m 52s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/160/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/605/ : SUCCESS in 48s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/182/ : SUCCESS in 3m 29s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/73/ : SUCCESS in 1m 19s

**Pull request merged**
