### PR TITLE
 FEATURE: BB-643 Add headlines secondary measure

### PR DESCRIPTION
**Pull request by petrjanu**

### CODE REVIEW

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by petrjanu** [comment]
@gooddata/react-components@5.0.0-petrjanu-pja-bb-643-2018-03-13T08-18-28-117Z

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/860/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/700/ : FAILURE in 1m 33s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/171/ : SUCCESS in 26s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/865/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/704/ : FAILURE in 2m 55s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/175/ : SUCCESS in 37s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/876/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/715/ : FAILURE in 1m 43s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/186/ : SUCCESS in 24s

**Comment by petrjanu** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/880/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/719/ : FAILURE in 2m 10s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/190/ : SUCCESS in 26s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/882/ : SUCCESS in 39s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/722/ : FAILURE in 2m 30s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/193/ : SUCCESS in 26s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/883/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/723/ : SUCCESS in 1m 06s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/194/ : SUCCESS in 30s

**Pull request closed without merging**
