### PR TITLE
RELATED: RAIL-694 verifikace

### PR DESCRIPTION
**Pull request by zbycz**

### CODE REVIEW

**Comment by zbycz** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/822/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/669/ : SUCCESS in 55s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/140/ : SUCCESS in 1m 35s

**Comment by osklive-kacatko** [comment]
Demo is running at https://client-demo.na.intgdc.com:50017/examples/

**Comment by osklive-kacatko** [comment]
Unable to comment the issue in JIRA, as the commit message doesn't contain JIRA id.

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/823/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/216/ : SUCCESS in 3m 51s

**Comment by zbycz** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/826/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/671/ : SUCCESS in 50s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/142/ : SUCCESS in 25s

**Comment by osklive-kacatko** [comment]
Source code updated. Using staging3.intgdc.com backend now. Demo has already been running at https://client-demo.na.intgdc.com:50017/examples/

**Comment by osklive-kacatko** [comment]
Unable to comment the issue in JIRA, as the commit message doesn't contain JIRA id.

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/827/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/218/ : SUCCESS in 2m 47s

**Pull request closed without merging**
