### PR TITLE
RELATED: RAIL-1389 SDK throws errors when used in custom app

### PR DESCRIPTION
**Pull request by Hurtak**
- gdc-goodstrap: https://github.com/gooddata/gdc-goodstrap/pull/939
- gooddata-react-components: https://github.com/gooddata/gooddata-react-components/pull/875
- gdc-app-components: https://github.com/gooddata/gdc-app-components/pull/527
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/1791
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2127

### CODE REVIEW

**Comment by Hurtak** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/3746/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/2996/ : SUCCESS in 15m 48s

**Comment by yenkins** [comment]
Link to Storybook test result:

https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/1602/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/3747/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-pull-request-dispatcher/992/ : SUCCESS in 23m 23s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/814/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/2998/ : SUCCESS in 16m 26s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/1603/ : SUCCESS in 18m 10s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/811/ : SUCCESS in 27m 23s

**Pull request merged**
