### PR TITLE
RELATED: RAIL-1337 properly count the aggregations in PivotTable

### PR DESCRIPTION
**Pull request by no23reason**

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/3107/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/2452/ : SUCCESS in 6m 42s

**Comment by tomasreichmann** [comment]
LGTM

**Comment by no23reason** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/664/ : SUCCESS in 28s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/2454/ : SUCCESS in 12m 17s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/1291/ : UNSTABLE in 19m 57s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/646/ : SUCCESS in 28m 38s

**Comment by yenkins** [comment]
Link to Storybook test result:

https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/1294/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/3110/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-pull-request-dispatcher/772/ : UNSTABLE in 19m 28s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/667/ : SUCCESS in 25s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/2458/ : SUCCESS in 6m 19s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/1295/ : UNSTABLE in 27m 56s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/649/ : SUCCESS in 22m 43s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/668/ : SUCCESS in 1m 19s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/2460/ : SUCCESS in 3m 17s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/1296/ : SUCCESS in 16m 56s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/650/ : SUCCESS in 11m 38s

**Pull request merged**
