### PR TITLE
RELATED: RAIL-620 Allow multiple date filters

### PR DESCRIPTION
**Pull request by vaclavbohac**
`3.0.1-vaclavbohac-allow-multiple-date-filters-2018-01-19T11-58-58-479Z`

### CODE REVIEW

**Comment by vaclavbohac** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/383/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/300/ : SUCCESS in 2m 43s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/84/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/384/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/97/ : SUCCESS in 4m 13s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/397/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/313/ : SUCCESS in 2m 37s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/118/ : SUCCESS in 58s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/315/ : SUCCESS in 1m 34s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/87/ : SUCCESS in 3m 41s

**Pull request merged**
