### PR TITLE
bump react-components in /examples

### PR DESCRIPTION
**Pull request by zbycz**

### CODE REVIEW

**Comment by zbycz** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1022/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/821/ : SUCCESS in 1m 01s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/294/ : SUCCESS in 2m 17s

**Comment by osklive-kacatko** [comment]
Demo is running at https://client-demo.na.intgdc.com:50036/examples/

**Comment by osklive-kacatko** [comment]
Unable to comment the issue in JIRA, as the commit message doesn't contain JIRA id.

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1023/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/288/ : SUCCESS in 4m 27s

**Comment by zbycz** [comment]
extended test - storybook

**Pull request closed without merging**
