### PR TITLE
TRIVIAL: Get rid of alpha tag in README

### PR DESCRIPTION
**Pull request by petrjanu**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/339/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/259/ : SUCCESS in 3m 15s

**Comment by vaclavbohac** [comment]
Morning, sir, `--access public` is used for publishing new packages, after that it does not do anything. Therefore it shouldn't be necessary to have it there.

**Comment by petrjanu** [comment]
Sir, I removed the argument. Please check, sir.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/342/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/262/ : SUCCESS in 1m 33s

**Comment by vaclavbohac** [comment]
@petrjanu Meanwhile it's necessary to use the alpha tag... again 😀

**Pull request closed without merging**
