### PR TITLE
FEATURE: ONE-3469, SD-170 update of translations

### PR DESCRIPTION
**Pull request by sitina**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/2625/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/2019/ : SUCCESS in 6m 20s

**Comment by lanhq** [comment]
There was an issue with SD-147 as #697.
So i think that we should not translate shorten numeric values.

**Comment by sitina** [comment]
ok, closing this; thank you for the heads up, @lanhq

**Comment by gdgate** [comment]
Build failed (check-teardown pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-stop-zuul-docker/306/ : FAILURE in 11m 54s

**Pull request closed without merging**
