### PR TITLE
RELATED: RAIL-732 Fix retrying on 401 response

### PR DESCRIPTION
**Pull request by vaclavbohac**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1277/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1038/ : SUCCESS in 3m 00s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/511/ : SUCCESS in 2m 28s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/233/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1039/ : SUCCESS in 2m 52s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/388/ : UNSTABLE in 7m 05s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/512/ : SUCCESS in 2m 38s

**Comment by vaclavbohac** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/389/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1278/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/359/ : SUCCESS in 8m 12s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/234/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1041/ : SUCCESS in 1m 30s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/391/ : SUCCESS in 6m 30s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/514/ : SUCCESS in 2m 21s

**Pull request merged**
