### PR TITLE
FEATURE: RAIL-587 Advanced examples

### PR DESCRIPTION
**Pull request by vaclavbohac**

### CODE REVIEW

**Comment by vaclavbohac** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/682/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/559/ : SUCCESS in 50s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/27/ : FAILURE in 1m 58s

**Comment by osklive-kacatko** [comment]
Demo is running at https://client-demo.na.intgdc.com:50036/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/683/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/177/ : SUCCESS in 2m 35s

**Pull request closed without merging**
