### PR TITLE
TRIVIAL: Revert version upgrade on wrong branch

### PR DESCRIPTION
**Pull request by Hurtak**
Alpha release was by mistake applied to `master` branch instead of `next-6.2.0` branch. @ivan-nejezchleb mentioned that it would be best to just revert this commit.

This commit reverts: https://github.com/gooddata/gooddata-react-components/commit/448f95d163311d272dbc006b49b5600ba664753b

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/2699/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/2080/ : SUCCESS in 7m 20s

**Comment by tomasreichmann** [comment]
LGTM

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/588/ : SUCCESS in 21s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/2112/ : SUCCESS in 13m 53s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/1119/ : UNSTABLE in 23m 26s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/558/ : SUCCESS in 22m 58s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/2736/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/2114/ : SUCCESS in 7m 05s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/590/ : SUCCESS in 30s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/2122/ : SUCCESS in 2m 31s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/1124/ : SUCCESS in 18m 30s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/560/ : SUCCESS in 18m 40s

**Pull request merged**
