### PR TITLE
RELATED: ONE-3503 Use updated goodstrap with fixed import

### PR DESCRIPTION
**Pull request by pbenes**

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/545/ : SUCCESS in 39s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/1951/ : SUCCESS in 24m 04s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/1031/ : UNSTABLE in 29m 33s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/506/ : SUCCESS in 22m 24s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/549/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/1956/ : SUCCESS in 4m 03s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/1036/ : UNSTABLE in 17m 00s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/510/ : SUCCESS in 20m 31s

**Comment by ivanmjartan** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/552/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/1959/ : SUCCESS in 3m 38s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/1039/ : SUCCESS in 14m 44s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/513/ : SUCCESS in 16m 26s

**Pull request merged**
