### PR TITLE
TRIVIAL: Update changelog for 6.2.0 release

### PR DESCRIPTION
**Pull request by petrjanu**
Updated changelog according to https://confluence.intgdc.com/display/GDUI/6.2.0

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/2806/ : SUCCESS in 45s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/2178/ : FAILURE in 12m 40s

**Comment by petrjanu** [comment]
ok to test

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by ivan-nejezchleb** [comment]
LGTM

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/604/ : SUCCESS in 26s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/2191/ : FAILURE in 4m 38s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/1153/ : UNSTABLE in 31m 58s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/576/ : SUCCESS in 14m 08s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/606/ : SUCCESS in 23s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/2200/ : SUCCESS in 5m 54s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/1157/ : SUCCESS in 17m 37s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/578/ : SUCCESS in 11m 38s

**Pull request merged**
