### PR TITLE
RELATED: RAIL-406 Remove string enums

### PR DESCRIPTION
**Pull request by vaclavbohac**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/36/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/675/ : SUCCESS in 1m 57s

**Comment by vaclavbohac** [comment]
`2.7.0-vaclavbohac-remove-string-enums-2017-10-23T11-52-43-439Z`

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/39/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/678/ : SUCCESS in 1m 41s

**Comment by vaclavbohac** [comment]
`2.7.0-vaclavbohac-remove-string-enums-2017-10-23T16-20-07-871Z`

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/41/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/680/ : SUCCESS in 55s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/45/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/684/ : SUCCESS in 1m 53s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/71/ : SUCCESS in 28s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/685/ : SUCCESS in 1m 03s

**Pull request merged**
