### PR TITLE
RELATED: ONE-3039 Combo chart

### PR DESCRIPTION
**Pull request by ivan-nejezchleb**

### CODE REVIEW

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1425/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1175/ : FAILURE in 33s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/648/ : SUCCESS in 2m 19s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1428/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1178/ : FAILURE in 31s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/651/ : SUCCESS in 2m 29s

**Comment by ivan-nejezchleb** [comment]
extended test - storybook

**Comment by ivan-nejezchleb** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/486/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1431/ : SUCCESS in 25s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/415/ : UNSTABLE in 8m 08s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1432/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1181/ : FAILURE in 31s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/654/ : SUCCESS in 2m 28s

**Comment by ivan-nejezchleb** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/487/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1433/ : SUCCESS in 21s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/416/ : UNSTABLE in 7m 42s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1440/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1188/ : SUCCESS in 1m 07s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/661/ : SUCCESS in 2m 37s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1443/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1191/ : SUCCESS in 1m 29s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/664/ : SUCCESS in 2m 15s

**Pull request closed without merging**
