### PR TITLE
RELATED: FET-56 Move Table from indigo-visualizations to react-components

### PR DESCRIPTION
**Pull request by ocetnik**
`5.1.0-ocetnik-doc-indigo-vis-table-in-ts-2018-05-04T07-28-36-404Z`

### CODE REVIEW

**Comment by ocetnik** [comment]
extended test - cafe

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/75/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/470/ : FAILURE in 14s

**Comment by ocetnik** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/74/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1326/ : FAILURE in 6m 05s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/799/ : FAILURE in 5m 39s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/76/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/471/ : FAILURE in 5m 16s

**Comment by ocetnik** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/77/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1327/ : SUCCESS in 2m 26s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/800/ : SUCCESS in 2m 34s

**Comment by ocetnik** [comment]
extended test - storybook

**Comment by yenkins** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/544/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/78/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/472/ : SUCCESS in 12m 33s

**Comment by tomasreichmann** [comment]
LGTM

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/8/ : SUCCESS in 22s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1334/ : SUCCESS in 3m 20s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/545/ : UNSTABLE in 13m 29s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/9/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1335/ : SUCCESS in 1m 24s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/546/ : SUCCESS in 14m 09s

**Pull request merged**
