### PR TITLE
FEATURE: FET-130 Apply Prettier on source code

### PR DESCRIPTION
**Pull request by xMort**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/3814/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/3070/ : SUCCESS in 19m 23s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/838/ : SUCCESS in 29s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/3071/ : SUCCESS in 24m 56s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/1637/ : SUCCESS in 23m 03s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/839/ : FAILURE in 29m 20s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/839/ : FAILURE in 17s
- gooddata-react-components-unit-tests-zuul-docker-el7 : SKIPPED
- gooddata-react-components-storybook-zuul-docker : SKIPPED
- gooddata-react-components-examples-zuul-docker : SKIPPED

**Comment by ivan-nejezchleb** [comment]
LGTM

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/840/ : SUCCESS in 21s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/3072/ : SUCCESS in 4m 00s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/1638/ : SUCCESS in 13m 07s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/840/ : FAILURE in 15m 07s

**Comment by xMort** [comment]
extended check - examples

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/3815/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/3073/ : SUCCESS in 7m 06s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-merge-compliance-check/841/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-unit-tests-zuul-docker-el7/3074/ : SUCCESS in 2m 42s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-storybook-zuul-docker/1639/ : SUCCESS in 17m 03s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-react-components-examples-zuul-docker/841/ : SUCCESS in 21m 59s

**Comment by tomasreichmann** [comment]
Čus Morte, já jsem do 15. V Izraeli. Řekni Danovi

**Pull request merged**
