### PR TITLE
RELATED: RAIL-670 Remove ErrorState.OK

### PR DESCRIPTION
**Pull request by vaclavbohac**
`5.0.0-vaclavbohac-remove-error-state-ok-2018-04-17T14-52-40-815Z`

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1285/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1045/ : SUCCESS in 2m 06s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/518/ : SUCCESS in 2m 28s

**Comment by vaclavbohac** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/395/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1286/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/363/ : UNSTABLE in 9m 26s

**Comment by vaclavbohac** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/399/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1294/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/366/ : SUCCESS in 6m 53s

**Comment by vaclavbohac** [comment]
`5.0.0-vaclavbohac-remove-error-state-ok-2018-04-13T14-49-35-694Z`

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1326/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1091/ : SUCCESS in 2m 38s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/564/ : SUCCESS in 2m 57s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1343/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1112/ : FAILURE in 2m 53s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/585/ : SUCCESS in 2m 31s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1358/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1120/ : FAILURE in 1m 39s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/593/ : FAILURE in 1m 56s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1359/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1121/ : FAILURE in 1m 47s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/594/ : SUCCESS in 3m 02s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1360/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1122/ : SUCCESS in 3m 22s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/595/ : SUCCESS in 2m 29s

**Comment by vaclavbohac** [comment]
`5.0.0-vaclavbohac-remove-error-state-ok-2018-04-17T14-52-40-815Z`

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1361/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1123/ : SUCCESS in 2m 44s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/596/ : SUCCESS in 2m 42s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1385/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1141/ : ABORTED in 5m 06s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/614/ : SUCCESS in 3m 01s

**Comment by vaclavbohac** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1386/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1142/ : SUCCESS in 2m 21s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/615/ : SUCCESS in 3m 11s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/273/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1143/ : SUCCESS in 2m 41s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/472/ : SUCCESS in 8m 05s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/616/ : SUCCESS in 2m 21s

**Pull request merged**
