### PR TITLE
RELATED: RAIL-529 Fix sorting & undo/redo

### PR DESCRIPTION
**Pull request by vaclavbohac**
Latest release: `3.0.0-vaclavbohac-sorting-2017-12-01T14-47-23-528Z`

### CODE REVIEW

**Comment by vaclavbohac** [comment]
`3.0.0-vaclavbohac-sorting-2017-12-01T14-47-23-528Z`

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/152/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/783/ : FAILURE in 1m 53s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/96/ : FAILURE in 1m 23s (non-voting)

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/153/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/784/ : FAILURE in 57s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/97/ : FAILURE in 2m 17s (non-voting)

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/154/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/785/ : FAILURE in 1m 45s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/98/ : FAILURE in 1m 18s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/155/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/786/ : SUCCESS in 59s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/99/ : SUCCESS in 1m 22s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/156/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/787/ : SUCCESS in 2m 00s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/100/ : SUCCESS in 2m 22s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/157/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/788/ : SUCCESS in 57s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/101/ : SUCCESS in 1m 21s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/158/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/789/ : SUCCESS in 1m 00s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/102/ : SUCCESS in 1m 21s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/77/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/790/ : SUCCESS in 1m 56s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/103/ : SUCCESS in 2m 15s (non-voting)

**Pull request merged**
