### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jansyk14**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/754/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 10s
- gooddata-react-components-unit-tests-zuul-docker-el7 : SKIPPED
- gooddata-react-components-examples-validation-zuul-docker-el7 : SKIPPED

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/755/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 8s
- gooddata-react-components-unit-tests-zuul-docker-el7 : SKIPPED
- gooddata-react-components-examples-validation-zuul-docker-el7 : SKIPPED

**Comment by vojty** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/773/ : ABORTED in 16s
- gooddata-react-components-pull-request-dispatcher : SKIPPED

**Comment by jansyk14** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/774/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 13s
- gooddata-react-components-pull-request-dispatcher : SKIPPED

**Comment by jansyk14** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/775/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 13s
- gooddata-react-components-unit-tests-zuul-docker-el7 : SKIPPED
- gooddata-react-components-examples-validation-zuul-docker-el7 : SKIPPED

**Pull request closed without merging**
