### PR TITLE
RELATED: RAIL 950 remove aggregation from measure definitions

### PR DESCRIPTION
**Pull request by tomasreichmann**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/274/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1513/ : SUCCESS in 2m 01s

**Comment by lhorak** [comment]
If it ain’t broken, don’t fix it.

**Comment by tomasreichmann** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-react-components-opensource-repository-check/361/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/528/ : FAILURE in 5m 55s

**Pull request closed without merging**
