### PR TITLE
TRIVIAL: Remove unnecessary test-storybook delay for BarChart

### PR DESCRIPTION
**Pull request by ocetnik**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/893/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/729/ : SUCCESS in 3m 51s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/200/ : SUCCESS in 2m 04s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/235/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/894/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/239/ : UNSTABLE in 5m 03s

**Comment by ocetnik** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/236/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/895/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/240/ : SUCCESS in 4m 42s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/185/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/732/ : SUCCESS in 2m 08s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/237/ : SUCCESS in 2m 25s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/205/ : SUCCESS in 1m 35s

**Pull request merged**
