### PR TITLE
BUGFIX: RAIL-676 Fix building examples

### PR DESCRIPTION
**Pull request by vaclavbohac**

### CODE REVIEW

**Comment by vaclavbohac** [comment]
extended test - examples

**Comment by osklive-kacatko** [comment]
Demo is running at https://client-demo.na.intgdc.com:50034/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/681/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/176/ : SUCCESS in 1m 31s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/680/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/558/ : SUCCESS in 49s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/26/ : SUCCESS in 2m 29s

**Comment by vaclavbohac** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/684/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/560/ : SUCCESS in 46s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/28/ : SUCCESS in 1m 22s

**Comment by osklive-kacatko** [comment]
Source code updated. Using staging3.intgdc.com backend now. Demo has already been running at https://client-demo.na.intgdc.com:50034/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/685/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/178/ : SUCCESS in 2m 44s

**Comment by vaclavbohac** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/686/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/561/ : SUCCESS in 51s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/29/ : SUCCESS in 1m 22s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/687/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/179/ : FAILURE in 42s

**Comment by vaclavbohac** [comment]
extended test - examples

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/688/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/562/ : SUCCESS in 46s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/30/ : SUCCESS in 1m 27s

**Comment by osklive-kacatko** [comment]
Source code updated. Using staging3.intgdc.com backend now. Demo has already been running at https://client-demo.na.intgdc.com:50034/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/689/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/180/ : SUCCESS in 2m 38s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/691/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/563/ : SUCCESS in 51s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/31/ : SUCCESS in 1m 34s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/702/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/570/ : SUCCESS in 1m 57s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/38/ : SUCCESS in 1m 19s

**Comment by vojty** [comment]
extended test - examples

**Comment by osklive-kacatko** [comment]
Source code updated. Using staging3.intgdc.com backend now. Demo has already been running at https://client-demo.na.intgdc.com:50034/examples/

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/703/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/185/ : SUCCESS in 3m 46s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/157/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/572/ : FAILURE in 3m 21s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/175/ : SUCCESS in 4m 51s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/40/ : SUCCESS in 2m 23s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/158/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/573/ : SUCCESS in 54s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/176/ : SUCCESS in 2m 22s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/41/ : SUCCESS in 1m 33s

**Pull request merged**
