### PR TITLE
RELATED: BB-328 table totals view mode

### PR DESCRIPTION
**Pull request by strouhaljan**
Waiting for new release of `gooddata-indigo-visualizations`. Related pull request: https://github.com/gooddata/gooddata-indigo-visualizations/pull/200

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/35/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/674/ : SUCCESS in 2m 02s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/37/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/676/ : SUCCESS in 2m 05s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/38/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/677/ : SUCCESS in 1m 56s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/51/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/691/ : SUCCESS in 2m 52s

**Comment by strouhaljan** [comment]
Passing Graphene & TestCafé tests:
https://github.com/gooddata/gdc-analytical-designer/pull/979
https://github.com/gooddata/gdc-dashboards/pull/1135

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/72/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-el7/692/ : SUCCESS in 2m 08s

**Pull request merged**
