### PR TITLE
RELATED: RAIL-694 rename prepare script in examples package.json as it must not run after each yarn install

### PR DESCRIPTION
**Pull request by langhammerp**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/782/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/630/ : SUCCESS in 57s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/101/ : SUCCESS in 1m 55s

**Comment by langhammerp** [comment]
extended test - examples

**Comment by osklive-kacatko** [comment]
Demo is running at https://client-demo.na.intgdc.com:50042/examples/

**Comment by osklive-kacatko** [comment]
Unable to comment the issue in JIRA, as the commit message doesn't contain JIRA id.

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/783/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/206/ : SUCCESS in 4m 30s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/784/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/631/ : SUCCESS in 45s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/102/ : SUCCESS in 1m 29s

**Comment by zbycz** [comment]
lgtm

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/164/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/632/ : SUCCESS in 45s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/190/ : SUCCESS in 3m 27s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/103/ : SUCCESS in 1m 42s

**Pull request merged**
