### PR TITLE
RELATED: BB-864, BB-821 Add value limit for tertiary item

### PR DESCRIPTION
**Pull request by martinmosko**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1289/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1047/ : SUCCESS in 1m 58s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/520/ : SUCCESS in 2m 57s

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/397/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1290/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/365/ : UNSTABLE in 7m 05s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1295/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1053/ : SUCCESS in 2m 18s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/526/ : SUCCESS in 5m 07s

**Comment by martinmosko** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/403/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1296/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-react-components-pull-request-dispatcher/367/ : SUCCESS in 7m 03s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-opensource-repository-check/1302/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1059/ : SUCCESS in 1m 19s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/532/ : SUCCESS in 2m 41s

**Comment by xMort** [comment]
lgtm

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/245/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1068/ : SUCCESS in 1m 17s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/412/ : UNSTABLE in 8m 05s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/541/ : SUCCESS in 2m 14s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/246/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1069/ : SUCCESS in 3m 19s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/413/ : UNSTABLE in 8m 01s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/542/ : SUCCESS in 3m 09s

**Comment by xMort** [comment]
lgtm

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-react-components-merge-compliance-check/248/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-react-components-unit-tests-zuul-docker-el7/1071/ : SUCCESS in 1m 22s
- https://ci.intgdc.com/job/gooddata-react-components-storybook-zuul-docker/416/ : SUCCESS in 7m 29s
- https://ci.intgdc.com/job/gooddata-react-components-examples-validation-zuul-docker-el7/544/ : SUCCESS in 2m 16s

**Pull request merged**
